service: aulamejor-api

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  env: ${file(./env.yml)}
  customDomain:
    basePath: "/"
    domainName: aulamejor.dotlabit.com
    stage: dev
    certificateName:
    createRoute53Record: true

provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  environment:
    mysqlHost: ${self:custom.env.mysqlHost}

functions:
  get_courses:
    name: ${self:custom.env.stage}_aulamejor_api_get_courses
    handler: api/get_courses/handler.main
    description: Collect Courses Info
    events:
      - http:
          path: /cursos
          method: get
          integration: lambda
          cors: true

#resources:
#  Resources:
#    ApiGatewayMethodInteractionidVarStatusGet:
#      Properties:
#        RequestParameters:
#          method.request.path.interaction_id: true
#        Integration:
#          RequestParameters:
#            integration.request.path.interaction_id: method.request.path.interaction_id
#          CacheNamespace: ApiGatewayMethodInteractionidVarStatusGetCacheNS
#          CacheKeyParameters: 
#            - method.request.path.interaction_id

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
